const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Question = require('../models/Question');
const connectDB = require('../config/db');

dotenv.config({ path: '../.env' }); // Assuming run from seed directory or backend root

const questions = [
  // --- UNIT 1: Introduction to IT Act 2000 ---
  { unit: 1, questionText: "Which section of the IT Act defines 'Computer'?", options: ["Sec 2(1)(i)", "Sec 2(1)(a)", "Sec 2(1)(t)", "Sec 2(1)(p)"], correctAnswer: 0, explanation: "Section 2(1)(i) defines a 'Computer' under the IT Act 2000.", sectionRef: "Sec 2(1)(i)", difficulty: "easy" },
  { unit: 1, questionText: "What is the primary objective of the IT Act 2000?", options: ["To regulate social media", "To grant legal recognition to electronic transactions", "To ban cryptocurrencies", "To provide free internet"], correctAnswer: 1, explanation: "The main objective is to provide legal recognition for transactions carried out by means of electronic data interchange and other means of electronic communication.", sectionRef: "Preamble", difficulty: "easy" },
  { unit: 1, questionText: "Under which section is the legal recognition of electronic records granted?", options: ["Sec 3", "Sec 4", "Sec 5", "Sec 10"], correctAnswer: 1, explanation: "Section 4 grants legal recognition of electronic records.", sectionRef: "Sec 4", difficulty: "medium" },
  { unit: 1, questionText: "Which section deals with the legal recognition of digital signatures?", options: ["Sec 3", "Sec 4", "Sec 5", "Sec 6"], correctAnswer: 2, explanation: "Section 5 deals with the legal recognition of digital signatures.", sectionRef: "Sec 5", difficulty: "medium" },
  { unit: 1, questionText: "Who appoints the Controller of Certifying Authorities (CCA)?", options: ["State Government", "Central Government", "Supreme Court", "President of India"], correctAnswer: 1, explanation: "The Central Government may, by notification in the Official Gazette, appoint a Controller of Certifying Authorities.", sectionRef: "Sec 17", difficulty: "easy" },
  { unit: 1, questionText: "What is the function of a Certifying Authority?", options: ["To issue Electronic Signature Certificates", "To monitor internet traffic", "To arrest cyber criminals", "To provide internet services"], correctAnswer: 0, explanation: "Certifying Authorities are licensed to issue electronic signature certificates.", sectionRef: "Sec 24", difficulty: "easy" },
  { unit: 1, questionText: "Which section outlines the retention of electronic records?", options: ["Sec 6", "Sec 7", "Sec 8", "Sec 9"], correctAnswer: 1, explanation: "Section 7 deals with the retention of electronic records.", sectionRef: "Sec 7", difficulty: "hard" },
  { unit: 1, questionText: "E-Commerce validity under the IT Act is primarily supported by which sections?", options: ["Sec 1-2", "Sec 3-10", "Sec 43-45", "Sec 66-67"], correctAnswer: 1, explanation: "Sections 3 to 10 deal with the authentication and legal recognition of electronic records and digital signatures, forming the basis of E-commerce validity.", sectionRef: "Sec 3-10", difficulty: "medium" },
  { unit: 1, questionText: "Which of the following is NOT covered under the IT Act 2000 initially?", options: ["Electronic Contracts", "Digital Signatures", "Will and Testament", "Cyber Crimes"], correctAnswer: 2, explanation: "A will as defined in the Indian Succession Act, 1925 is excluded from the applicability of the IT Act.", sectionRef: "First Schedule", difficulty: "medium" },
  { unit: 1, questionText: "Section 10A of the IT Act deals with:", options: ["Validity of contracts formed through electronic means", "Penalty for damage to computer", "Electronic signature", "Cyber Appellate Tribunal"], correctAnswer: 0, explanation: "Section 10A provides legislative authority to E-contracts.", sectionRef: "Sec 10A", difficulty: "hard" },

  // --- UNIT 2: Cyber Offences & Penalties ---
  { unit: 2, questionText: "Which section imposes a penalty for damage to computer, computer system, etc.?", options: ["Sec 43", "Sec 66", "Sec 67", "Sec 72"], correctAnswer: 0, explanation: "Section 43 deals with penalty and compensation for damage to computer, computer system, etc.", sectionRef: "Sec 43", difficulty: "easy" },
  { unit: 2, questionText: "What is the maximum compensation under Section 43 for civil liability?", options: ["₹10 Lakh", "₹50 Lakh", "₹1 Crore", "No Limit / Proportionate to damage"], correctAnswer: 3, explanation: "Originally up to ₹1 Crore, but the IT Amendment Act 2008 removed the upper limit, making it proportionate to the damage.", sectionRef: "Sec 43", difficulty: "hard" },
  { unit: 2, questionText: "Tampering with computer source documents is punishable under which section?", options: ["Sec 65", "Sec 66", "Sec 67", "Sec 71"], correctAnswer: 0, explanation: "Section 65 deals with tampering with computer source documents.", sectionRef: "Sec 65", difficulty: "medium" },
  { unit: 2, questionText: "What is the punishment for tampering with source code under Sec 65?", options: ["1 year or ₹1 Lakh", "2 years or ₹2 Lakhs", "3 years or ₹2 Lakhs", "5 years or ₹5 Lakhs"], correctAnswer: 2, explanation: "Imprisonment up to 3 years, or with fine which may extend up to two lakh rupees, or with both.", sectionRef: "Sec 65", difficulty: "hard" },
  { unit: 2, questionText: "Which section deals with computer related offences (hacking)?", options: ["Sec 65", "Sec 66", "Sec 67", "Sec 68"], correctAnswer: 1, explanation: "Section 66 deals with computer related offences, which essentially covers acts referred to in Section 43 if done dishonestly or fraudulently.", sectionRef: "Sec 66", difficulty: "easy" },
  { unit: 2, questionText: "Section 66A (offensive messages) was struck down by the Supreme Court in which landmark case?", options: ["Puttaswamy case", "Shreya Singhal case", "Navtej Johar case", "Anuradha Bhasin case"], correctAnswer: 1, explanation: "Section 66A was struck down in Shreya Singhal v. Union of India (2015) for violating Article 19(1)(a).", sectionRef: "Sec 66A", difficulty: "easy" },
  { unit: 2, questionText: "Which section deals with identity theft?", options: ["Sec 43", "Sec 66B", "Sec 66C", "Sec 66D"], correctAnswer: 2, explanation: "Section 66C deals with punishment for identity theft.", sectionRef: "Sec 66C", difficulty: "medium" },
  { unit: 2, questionText: "Cheating by personation by using computer resource is covered under:", options: ["Sec 66B", "Sec 66C", "Sec 66D", "Sec 66E"], correctAnswer: 2, explanation: "Section 66D deals with punishment for cheating by personation by using computer resource.", sectionRef: "Sec 66D", difficulty: "medium" },
  { unit: 2, questionText: "Which section addresses the violation of privacy (voyeurism)?", options: ["Sec 66E", "Sec 67", "Sec 67A", "Sec 72"], correctAnswer: 0, explanation: "Section 66E deals with punishment for violation of privacy (capturing/publishing images of private areas).", sectionRef: "Sec 66E", difficulty: "medium" },
  { unit: 2, questionText: "Cyber terrorism is punishable under which section of the IT Act?", options: ["Sec 66F", "Sec 67", "Sec 69", "Sec 70"], correctAnswer: 0, explanation: "Section 66F provides punishment for cyber terrorism (up to life imprisonment).", sectionRef: "Sec 66F", difficulty: "easy" },

  // --- UNIT 3: Data Protection & Privacy ---
  { unit: 3, questionText: "Which section mandates reasonable security practices for handling sensitive personal data?", options: ["Sec 43", "Sec 43A", "Sec 72", "Sec 79"], correctAnswer: 1, explanation: "Section 43A deals with compensation for failure to protect data by a body corporate.", sectionRef: "Sec 43A", difficulty: "easy" },
  { unit: 3, questionText: "What do the SPDI Rules 2011 govern?", options: ["E-commerce transactions", "Sensitive Personal Data or Information", "Digital Signatures", "Cyber Appellate Tribunal"], correctAnswer: 1, explanation: "SPDI Rules govern the collection, disclosure, and handling of Sensitive Personal Data or Information.", sectionRef: "SPDI Rules 2011", difficulty: "medium" },
  { unit: 3, questionText: "Which of the following is considered Sensitive Personal Data under SPDI Rules?", options: ["Name", "Email Address", "Passwords", "Office Address"], correctAnswer: 2, explanation: "Passwords, financial information, biometric data, etc., are considered sensitive personal data.", sectionRef: "SPDI Rules 2011", difficulty: "medium" },
  { unit: 3, questionText: "Section 72 deals with the penalty for:", options: ["Identity theft", "Breach of confidentiality and privacy", "Hacking", "Cyber terrorism"], correctAnswer: 1, explanation: "Section 72 deals with penalty for breach of confidentiality and privacy by any person who has secured access to electronic records/data in pursuance of powers under the Act.", sectionRef: "Sec 72", difficulty: "easy" },
  { unit: 3, questionText: "What is the penalty under Section 72 for breach of confidentiality?", options: ["1 year or ₹1 Lakh", "2 years or ₹1 Lakh", "3 years or ₹5 Lakhs", "5 years or ₹10 Lakhs"], correctAnswer: 1, explanation: "Imprisonment up to 2 years, or fine up to ₹1 Lakh, or both.", sectionRef: "Sec 72", difficulty: "hard" },
  { unit: 3, questionText: "Section 72A pertains to:", options: ["Disclosure of info in breach of lawful contract", "Tampering with computer source", "Publishing obscene material", "Interception of messages"], correctAnswer: 0, explanation: "Section 72A deals with punishment for disclosure of information in breach of lawful contract.", sectionRef: "Sec 72A", difficulty: "medium" },
  { unit: 3, questionText: "The maximum punishment under Section 72A is:", options: ["1 year or ₹2 Lakhs", "2 years or ₹5 Lakhs", "3 years or ₹5 Lakhs", "5 years or ₹10 Lakhs"], correctAnswer: 2, explanation: "Imprisonment up to 3 years, or fine up to ₹5 Lakhs, or both.", sectionRef: "Sec 72A", difficulty: "hard" },
  { unit: 3, questionText: "Which recent Indian legislation focuses entirely on data protection, superseding some IT Act provisions?", options: ["DPDP Act 2023", "IT Amendment Act 2021", "Data Privacy Rules 2020", "Cyber Security Act 2022"], correctAnswer: 0, explanation: "The Digital Personal Data Protection (DPDP) Act 2023 is the comprehensive data protection law.", sectionRef: "DPDP Act 2023", difficulty: "easy" },
  { unit: 3, questionText: "Under Section 43A, who is liable to pay compensation?", options: ["An individual", "A body corporate", "The Government", "The Internet Service Provider"], correctAnswer: 1, explanation: "A 'body corporate' that is negligent in implementing and maintaining reasonable security practices.", sectionRef: "Sec 43A", difficulty: "medium" },
  { unit: 3, questionText: "Which of the following is NOT typically classified as 'Sensitive Personal Data'?", options: ["Biometric information", "Sexual orientation", "Financial information", "Publicly available professional profile"], correctAnswer: 3, explanation: "Information that is freely available or accessible in the public domain is not considered sensitive personal data.", sectionRef: "SPDI Rules 2011", difficulty: "medium" },

  // --- UNIT 4: Intermediary Liability & E-Governance ---
  { unit: 4, questionText: "Which section provides a 'safe harbour' for intermediaries?", options: ["Sec 69", "Sec 72", "Sec 79", "Sec 80"], correctAnswer: 2, explanation: "Section 79 provides exemption from liability of intermediary in certain cases.", sectionRef: "Sec 79", difficulty: "easy" },
  { unit: 4, questionText: "An intermediary loses safe harbour protection under Sec 79 if they:", options: ["Act merely as a conduit", "Fail to observe due diligence", "Provide access to a communication system", "Store user data temporarily"], correctAnswer: 1, explanation: "If they fail to observe due diligence guidelines or upon receiving actual knowledge of unlawful acts, fail to take down content, they lose protection.", sectionRef: "Sec 79", difficulty: "medium" },
  { unit: 4, questionText: "The IT (Intermediary Guidelines) Rules were significantly updated in which year to regulate social media?", options: ["2011", "2015", "2021", "2023"], correctAnswer: 2, explanation: "The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 imposed stricter due diligence on Significant Social Media Intermediaries.", sectionRef: "IT Rules 2021", difficulty: "medium" },
  { unit: 4, questionText: "Section 69 gives power to the Government for:", options: ["Blocking websites", "Interception, monitoring, or decryption of any information", "Regulating e-commerce", "Issuing digital signatures"], correctAnswer: 1, explanation: "Section 69 deals with power to issue directions for interception or monitoring or decryption of any information through any computer resource.", sectionRef: "Sec 69", difficulty: "medium" },
  { unit: 4, questionText: "What is the penalty for a subscriber or intermediary failing to assist the agency under Section 69?", options: ["3 years imprisonment", "5 years imprisonment", "7 years imprisonment", "Fine only"], correctAnswer: 2, explanation: "Failure to assist the agency shall be punished with imprisonment for a term which may extend to seven years and shall also be liable to fine.", sectionRef: "Sec 69", difficulty: "hard" },
  { unit: 4, questionText: "Which section empowers the Government to block public access to information (website blocking)?", options: ["Sec 69", "Sec 69A", "Sec 69B", "Sec 70"], correctAnswer: 1, explanation: "Section 69A grants the power to issue directions for blocking for public access of any information through any computer resource.", sectionRef: "Sec 69A", difficulty: "easy" },
  { unit: 4, questionText: "Which of the following is a valid ground for blocking a website under Sec 69A?", options: ["Copyright infringement", "Defamation", "Interest of sovereignty and integrity of India", "Unfair trade practices"], correctAnswer: 2, explanation: "Grounds under 69A include sovereignty and integrity of India, defense, security of the State, friendly relations with foreign States or public order.", sectionRef: "Sec 69A", difficulty: "hard" },
  { unit: 4, questionText: "Sections 4 to 10 of the IT Act primarily deal with the framework for:", options: ["Cyber terrorism", "E-Governance", "Intermediary liability", "Data protection"], correctAnswer: 1, explanation: "These sections provide legal recognition to electronic records, digital signatures, use of electronic records in Government, etc., forming the E-Governance framework.", sectionRef: "Sec 4-10", difficulty: "medium" },
  { unit: 4, questionText: "What does 'due diligence' by intermediaries imply under the IT Rules?", options: ["Publishing privacy policy and terms of use", "Moderating all user content before posting", "Providing free internet", "Paying taxes on user generated content"], correctAnswer: 0, explanation: "Due diligence includes publishing rules and regulations, privacy policy, and user agreements.", sectionRef: "IT Rules 2021", difficulty: "medium" },
  { unit: 4, questionText: "Can an intermediary be held liable if they initiate the transmission of unlawful content?", options: ["Yes, always", "No, never", "Only if it involves national security", "Only if it is defamatory"], correctAnswer: 0, explanation: "Safe harbour under 79(1) does not apply if the intermediary initiates the transmission, selects the receiver, or modifies the information.", sectionRef: "Sec 79(2)", difficulty: "hard" },

  // --- UNIT 5: Cyber Crime Investigation & Evidence ---
  { unit: 5, questionText: "Which section deals with the power of an Adjudicating Officer to hold an inquiry?", options: ["Sec 43", "Sec 46", "Sec 66", "Sec 79"], correctAnswer: 1, explanation: "Section 46 deals with the power to adjudicate and hold an inquiry for contraventions where penalties are imposed.", sectionRef: "Sec 46", difficulty: "medium" },
  { unit: 5, questionText: "Section 77 of the IT Act clarifies that:", options: ["No penalty under IT Act prevents prosecution under other laws", "IT Act overrides IPC", "All cyber crimes are non-bailable", "Police can search without warrant in all cases"], correctAnswer: 0, explanation: "Section 77 states that compensation or penalties under the IT Act do not interfere with any other punishment under any other law.", sectionRef: "Sec 77", difficulty: "hard" },
  { unit: 5, questionText: "Which section of the Indian Evidence Act is crucial for the admissibility of electronic evidence?", options: ["Sec 65A", "Sec 65B", "Sec 66", "Sec 67"], correctAnswer: 1, explanation: "Section 65B of the Indian Evidence Act details the conditions for admissibility of electronic records.", sectionRef: "IEA Sec 65B", difficulty: "easy" },
  { unit: 5, questionText: "A certificate under Section 65B(4) of the Evidence Act is required to:", options: ["Prove identity of the accused", "Identify the computer producing the electronic record", "Prove the age of the victim", "Authorize a police search"], correctAnswer: 1, explanation: "The certificate identifies the electronic record, describes the manner of its production, and gives particulars of the device.", sectionRef: "IEA Sec 65B(4)", difficulty: "medium" },
  { unit: 5, questionText: "What is the primary national portal for reporting cyber crimes in India?", options: ["cert-in.org", "cybercrime.gov.in", "ncrb.gov.in", "mha.gov.in"], correctAnswer: 1, explanation: "cybercrime.gov.in is the National Cyber Crime Reporting Portal.", sectionRef: "Reporting", difficulty: "easy" },
  { unit: 5, questionText: "What does CERT-In stand for?", options: ["Computer Emergency Response Team - India", "Cyber Evaluation and Reporting Taskforce - India", "Central Electronic Record Tracker - India", "Crime Evidence Resource Team - India"], correctAnswer: 0, explanation: "CERT-In is the national nodal agency for responding to computer security incidents as and when they occur.", sectionRef: "CERT-In", difficulty: "easy" },
  { unit: 5, questionText: "In digital forensics, what ensures that evidence has not been tampered with since collection?", options: ["Antivirus scan", "Hash verification (e.g., MD5, SHA)", "Encryption", "Firewall logs"], correctAnswer: 1, explanation: "Hash verification creates a unique digital fingerprint of the data; any change to the data changes the hash.", sectionRef: "Forensics", difficulty: "medium" },
  { unit: 5, questionText: "What is the 'Chain of Custody' in cyber crime investigation?", options: ["A list of passwords", "A chronological documentation of evidence handling", "A network topology map", "The hierarchy of police officers"], correctAnswer: 1, explanation: "Chain of custody is the chronological documentation showing the seizure, custody, control, transfer, analysis, and disposition of evidence.", sectionRef: "Forensics", difficulty: "medium" },
  { unit: 5, questionText: "Can an Inspector of Police investigate offences under the IT Act?", options: ["Yes, for all offences", "Yes, but originally it was restricted to DSP/ACP and above", "No, only CBI can investigate", "No, only cyber experts can investigate"], correctAnswer: 1, explanation: "Originally Section 78 restricted investigation to DSP and above, but the 2008 Amendment allowed Inspectors to investigate.", sectionRef: "Sec 78", difficulty: "hard" },
  { unit: 5, questionText: "Is electronic evidence primary or secondary evidence under the Indian Evidence Act?", options: ["Always primary", "Always secondary", "Treated as documentary evidence subject to Sec 65B", "Not admissible"], correctAnswer: 2, explanation: "Electronic records are documentary evidence, and their admissibility is governed by the special provisions of Sec 65B.", sectionRef: "IEA Sec 65B", difficulty: "hard" },

  // --- UNIT 6: Emerging Issues in Cyber Law ---
  { unit: 6, questionText: "Which cyber threat involves encrypting a victim's files and demanding payment for the decryption key?", options: ["Phishing", "Ransomware", "DDoS", "Spyware"], correctAnswer: 1, explanation: "Ransomware holds data hostage until a ransom is paid.", sectionRef: "Emerging Threats", difficulty: "easy" },
  { unit: 6, questionText: "Under which IT Act section can Ransomware attacks be primarily prosecuted for damaging computer data?", options: ["Sec 43 / 66", "Sec 66C", "Sec 66E", "Sec 67"], correctAnswer: 0, explanation: "Ransomware alters/destroys data, which falls under Sec 43 and is a punishable offence under Sec 66.", sectionRef: "Sec 43/66", difficulty: "medium" },
  { unit: 6, questionText: "What legal issue do Deepfakes primarily raise under the IT Act?", options: ["Copyright violation only", "Identity theft, impersonation, and violation of privacy (Sec 66C, 66D, 66E)", "Tax evasion", "E-commerce fraud"], correctAnswer: 1, explanation: "Deepfakes often involve identity theft (66C), cheating by personation (66D), and violating privacy (66E).", sectionRef: "Sec 66C-E", difficulty: "medium" },
  { unit: 6, questionText: "The 'Right to be Forgotten' in India currently draws its legal basis primarily from:", options: ["The IT Act 2000 preamble", "The fundamental right to privacy (Art 21) as recognized in Puttaswamy case", "The Indian Contract Act", "Section 66A of IT Act"], correctAnswer: 1, explanation: "The Supreme Court recognized the Right to Privacy, including the Right to be Forgotten, under Article 21.", sectionRef: "Constitutional Law", difficulty: "hard" },
  { unit: 6, questionText: "What is India's current legislative stance on Cryptocurrencies (as of 2023-24)?", options: ["Completely banned under IT Act", "Recognized as legal tender", "Regulated under taxation and anti-money laundering laws (PMLA) without specific crypto legislation", "Regulated by the RBI as fiat currency"], correctAnswer: 2, explanation: "While not explicitly banned, they are taxed heavily and brought under the ambit of the Prevention of Money Laundering Act (PMLA).", sectionRef: "Emerging Tech", difficulty: "hard" },
  { unit: 6, questionText: "Who is liable for a contract formed autonomously by an AI system?", options: ["The AI itself", "The software developer, deployer, or user depending on the context and existing contract laws", "The ISP", "No one, AI contracts are void"], correctAnswer: 1, explanation: "AI liability is a grey area, but traditionally liability falls on the human or corporate entity controlling or deploying the AI.", sectionRef: "AI & Law", difficulty: "medium" },
  { unit: 6, questionText: "Phishing is a form of:", options: ["Hardware damage", "Social engineering / Cheating by personation", "Denial of Service", "Wireless hacking"], correctAnswer: 1, explanation: "Phishing tricks users into revealing information, often falling under cheating by personation (Sec 66D).", sectionRef: "Sec 66D", difficulty: "easy" },
  { unit: 6, questionText: "If a social media platform fails to remove a deepfake video within 24 hours of a complaint by a victim, what happens?", options: ["Platform is banned in India", "Platform loses its safe harbour protection under Sec 79", "The CEO is immediately arrested", "Nothing happens"], correctAnswer: 1, explanation: "Under the IT Rules 2021, failing to act on grievances rapidly, especially regarding non-consensual imagery/deepfakes, strips the intermediary of safe harbour.", sectionRef: "IT Rules 2021", difficulty: "medium" },
  { unit: 6, questionText: "Which authority frequently issues advisories regarding emerging threats like ransomware and zero-day vulnerabilities in India?", options: ["NITI Aayog", "CERT-In", "CBI", "Supreme Court"], correctAnswer: 1, explanation: "CERT-In is responsible for issuing guidelines, advisories, and vulnerability notes.", sectionRef: "CERT-In", difficulty: "easy" },
  { unit: 6, questionText: "The liability of autonomous vehicles (AI) in case of an accident tests the boundaries of which traditional legal concept?", options: ["Strict Liability / Tort Law", "Intellectual Property", "Freedom of Speech", "Digital Signatures"], correctAnswer: 0, explanation: "When an AI causes harm without direct human instruction, it challenges traditional tort concepts of negligence and strict liability.", sectionRef: "AI Liability", difficulty: "hard" }
];

const seedDB = async () => {
  try {
    // Determine path to .env file relative to this script
    // If running from backend directory: node seed/seedQuestions.js
    require('dotenv').config(); 
    
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });
    console.log('MongoDB Connected for Seeding');

    await Question.deleteMany(); // Clear existing questions
    console.log('Existing questions removed');

    await Question.insertMany(questions);
    console.log('60 Questions successfully seeded!');

    process.exit();
  } catch (error) {
    console.error('Error seeding questions:', error);
    process.exit(1);
  }
};

seedDB();
